kibot:
  version: 1

filters:
  - name: only_jlc_parts
    comment: 'Only parts with JLC code'
    type: generic
    include_only:
      - column: 'LCSC#'
        regex: '^C\d+'
  - name: exclude_e22_and_esp32
    comment: 'Exclude E22 and ESP32 modules from CPL'
    type: generic
    exclude_refs:
      - U3
      - U1
  - name: exclude_auto_prog
    comment: 'Exclude auto programming circuit from CPL'
    type: generic
    exclude_refs:
      - R3
      - R4
      - Q1
      - Q2
  - name: exclude_psram
    comment: 'Exclude psram circuit from CPL'
    type: generic
    exclude_refs:
      - R6
      - U2
      
variants:
  - name: rotated
    comment: 'Just a place holder for the rotation filter'
    type: kibom
    variant: rotated
    pre_transform: _rot_footprint

outputs:
  - name: 'position'
    comment: "Pick and place file, JLC style"
    type: position
    options:
      variant: rotated
      output: '%f_cpl_jlc.%x'
      format: CSV
      units: millimeters
      separate_files_for_front_and_back: false
      only_smd: true
      dnf_filter: 'exclude_e22_and_esp32'
      columns:
        - id: Ref
          name: Designator
        - Val
        - Package
        - id: PosX
          name: "Mid X"
        - id: PosY
          name: "Mid Y"
        - id: Rot
          name: Rotation
        - id: Side
          name: Layer
          
  - name: 'position (no auto-prog)'
    comment: "Pick and place file, JLC style (no auto-prog)"
    type: position
    options:
      variant: rotated
      output: '%f_cpl_jlc_no_auto_prog.%x'
      format: CSV
      units: millimeters
      separate_files_for_front_and_back: false
      only_smd: true
      dnf_filter: 
        - 'exclude_e22_and_esp32'
        - 'exclude_auto_prog'
      columns:
        - id: Ref
          name: Designator
        - Val
        - Package
        - id: PosX
          name: "Mid X"
        - id: PosY
          name: "Mid Y"
        - id: Rot
          name: Rotation
        - id: Side
          name: Layer
          
  - name: 'position (no psram)'
    comment: "Pick and place file, JLC style (no psram)"
    type: position
    options:
      variant: rotated
      output: '%f_cpl_jlc_no_psram.%x'
      format: CSV
      units: millimeters
      separate_files_for_front_and_back: false
      only_smd: true
      dnf_filter: 
        - 'exclude_e22_and_esp32'
        - 'exclude_psram'
      columns:
        - id: Ref
          name: Designator
        - Val
        - Package
        - id: PosX
          name: "Mid X"
        - id: PosY
          name: "Mid Y"
        - id: Rot
          name: Rotation
        - id: Side
          name: Layer

          
  - name: 'position (min parts)'
    comment: "Pick and place file, JLC style (minimum parts)"
    type: position
    options:
      variant: rotated
      output: '%f_cpl_jlc_min_parts.%x'
      format: CSV
      units: millimeters
      separate_files_for_front_and_back: false
      only_smd: true
      dnf_filter: 
        - 'exclude_e22_and_esp32'
        - 'exclude_psram'
        - 'exclude_auto_prog'
      columns:
        - id: Ref
          name: Designator
        - Val
        - Package
        - id: PosX
          name: "Mid X"
        - id: PosY
          name: "Mid Y"
        - id: Rot
          name: Rotation
        - id: Side
          name: Layer
          
  - name: 'bom'
    comment: "BoM for JLC"
    type: bom
    options:
      output: '%f_%i_jlc.%x'
      exclude_filter: 'only_jlc_parts'
      ref_separator: ','
      columns:
        - field: Value
          name: Comment
        - field: References
          name: Designator
        - Footprint
        - field: 'LCSC#'
          name: 'LCSC Part #'
      csv:
        hide_pcb_info: true
        hide_stats_info: true
        quote_all: true

  - name: 'interactive_bom'
    comment: "Interactive Bill of Materials (HTML)"
    type: ibom
    dir: BoM
    options:
      blacklist: 'DNF*'
      name_format: '%f_iBoM'
