kibot:
  version: 1

filters:
  - name: only_jlc_parts
    comment: 'Only parts with JLC code'
    type: generic
    include_only:
      - column: 'LCSC#'
        regex: '^C\d+'
  - name: exclude_e22_and_esp32
    comment: 'Exclude E22 and ESP32 modules from CPL'
    type: generic
    exclude_refs:
      - U3
      - U1
  - name: exclude_gps_power_enable
    comment: 'Exclude GPS power switching (and J1+J2)'
    type: generic
    exclude_refs:
      - R10
      - R16
      - J1
      - J2

variants:
  - name: '%variant'
    comment: 'Variant board components for pick and place'
    type: kibom
    file_id: %variant
    variant: %variant

  - name: 'rotated'
    comment: 'Just a place holder for the rotation filter'
    type: kibom
    variant: rotated
    pre_transform: _rot_footprint

outputs:
       
  - name: 'position'
    comment: 'Pick and place file, JLC style'
    type: position
    options:
      variant: %variant
      dnf_filter: 
        - 'exclude_e22_and_esp32'
        - 'exclude_gps_power_enable'
      output: 'CPL-JLCPCB.%x'
      format: CSV
      units: millimeters
      separate_files_for_front_and_back: false
      only_smd: true
      columns:
        - id: Ref
          name: Designator
        - Val
        - Package
        - id: PosX
          name: "Mid X"
        - id: PosY
          name: "Mid Y"
        - id: Rot
          name: Rotation
        - id: Side
          name: Layer

  - name: 'bom'
    comment: "BoM for JLC/LCSC"
    type: bom
    options:
      variant: %variant
      output: 'BoM-JLCPCB.%x'
      exclude_filter: 'only_jlc_parts'
      ref_separator: ','
      columns:
        - field: Value
          name: Comment
        - field: References
          name: Designator
        - Footprint
        - field: 'LCSC#'
          name: 'LCSC Part #'
      csv:
        hide_pcb_info: true
        hide_stats_info: true
        quote_all: true

  - name: 'interactive_bom'
    type: ibom
    options:
      variant: %variant
      blacklist: 'DNF*'
      dnf_filter:
        - 'exclude_gps_power_enable'
      output: 'Interactive-BoM.html'
  
  - name: 'schematic'
    type: pdf_sch_print
    dir: .
    options:
      variant: %variant
      output: Schematic.pdf