kibot:
  version: 1

filters:
  - name: only_jlc_parts
    comment: 'Only parts with JLC code'
    type: generic
    include_only:
      - column: 'LCSC#'
        regex: '^C\d+'
  - name: exclude_e22_and_esp32
    comment: 'Exclude E22 and ESP32 modules from CPL'
    type: generic
    exclude_refs:
      - U3
      - U1

variants:
  - name: 'core'
    comment: 'Core board components for pick and place'
    type: kibom
    file_id: core
    variant: core

  - name: 'rotated'
    comment: 'Just a place holder for the rotation filter'
    type: kibom
    variant: rotated
    pre_transform: _rot_footprint

outputs:
       
  - name: 'position (core)'
    comment: "Pick and place file, JLC style (minimum core parts)"
    type: position
    options:
      variant: core
      dnf_filter: 'exclude_e22_and_esp32'
      output: '%f_cpl_jlc.%x'
      format: CSV
      units: millimeters
      separate_files_for_front_and_back: false
      only_smd: true
      columns:
        - id: Ref
          name: Designator
        - Val
        - Package
        - id: PosX
          name: "Mid X"
        - id: PosY
          name: "Mid Y"
        - id: Rot
          name: Rotation
        - id: Side
          name: Layer

  - name: 'bom (core)'
    comment: "BoM for JLC/LCSC"
    type: bom
    options:
      variant: core
      output: '%f_%i_jlc.%x'
      exclude_filter: 'only_jlc_parts'
      ref_separator: ','
      columns:
        - field: Value
          name: Comment
        - field: References
          name: Designator
        - Footprint
        - field: 'LCSC#'
          name: 'LCSC Part #'
      csv:
        hide_pcb_info: true
        hide_stats_info: true
        quote_all: true

  - name: 'interactive_bom (core)'
    type: ibom
    options:
      variant: core
      blacklist: 'DNF*'
      name_format: '%f_iBoM'
  
  - name: 'schematic (core)'
    type: pdf_sch_print
    dir: .
    options:
      variant: core
      output: Schematic.pdf