kibot:
  version: 1

  
filters:
  - name: only_jlc_parts
    comment: 'Only parts with JLC code'
    type: generic
    include_only:
      - column: 'LCSC#'
        regex: '^C\d+'
  - name: exclude_e22_and_esp32
    comment: 'Exclude E22 and ESP32 modules from CPL'
    type: generic
    exclude_refs:
      - U3
      - U1
  - name: exclude_gps_power_enable
    comment: 'Exclude GPS power switching (and J1+J2)'
    type: generic
    exclude_refs:
      - R10
      - R16
      - J1
      - J2

variants:
  - name: 'default'
    comment: 'Full schematic'
    type: kibom

  - name: 'rotated'
    comment: 'Just a place holder for the rotation filter'
    type: kibom
    variant: rotated
    pre_transform: _rot_footprint

outputs:

  - name: board_top
    comment: "Top layer view"
    type: pcbdraw
    options:
      format: jpg
      dpi: 300
      output: PCB-Top.jpg

  - name: board_bottom
    comment: "Bottom layer view"
    type: pcbdraw
    options:
      format: jpg
      dpi: 300
      bottom: true
      output: PCB-Bottom.jpg

  - name: 3D
    comment: "STEP 3D model"
    type: step
    options:
      output: PCB-Model.stp

  - name: JLCPCB_gerbers
    comment: Gerbers compatible with JLCPCB
    type: gerber
    dir: JLCPCB
    options: &gerber_options
      exclude_edge_layer: true
      exclude_pads_from_silkscreen: true
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: false
      force_plot_invisible_refs_vals: false
      tent_vias: true
      use_protel_extensions: true
      create_gerber_job_file: false
      disable_aperture_macros: true
      gerber_precision: 4.6
      use_gerber_x2_attributes: false
      use_gerber_net_attributes: false
      line_width: 0.1
      subtract_mask_from_silk: true
      inner_extension_pattern: '.gp%n'
    layers:
      # Note: a more generic approach is to use 'copper' but then the filenames
      # are slightly different.
      - F.Cu
      - B.Cu
      - F.SilkS
      - B.SilkS
      - F.Mask
      - B.Mask
      - Edge.Cuts

  - name: JLCPCB_drill
    comment: Drill files compatible with JLCPCB
    type: excellon
    dir: JLCPCB
    options:
      pth_and_npth_single_file: false
      pth_id: '-PTH'
      npth_id: '-NPTH'
      metric_units: true
      map: gerber
      route_mode_for_oval_holes: false
      output: "%f%i.%x"

  - name: JLCPCB
    comment: ZIP file for JLCPCB
    type: compress
    dir: JLCPCB
    options:
      files:
        - from_output: JLCPCB_gerbers
          dest: /
        - from_output: JLCPCB_drill
          dest: /

  - name: 'position (default)'
    comment: "Pick and place file, JLC style"
    type: position
    options:
      variant: rotated
      dnf_filter:
        - 'exclude_e22_and_esp32'
        - 'exclude_gps_power_enable'
      output: '%f_cpl_jlc.%x'
      format: CSV
      units: millimeters
      separate_files_for_front_and_back: false
      only_smd: true
      columns:
        - id: Ref
          name: Designator
        - Val
        - Package
        - id: PosX
          name: "Mid X"
        - id: PosY
          name: "Mid Y"
        - id: Rot
          name: Rotation
        - id: Side
          name: Layer
            
  - name: 'bom (default)'
    comment: "BoM for JLC/LCSC"
    type: bom
    options:
      output: '%f_%i_jlc.%x'
      exclude_filter: 'only_jlc_parts'
      ref_separator: ','
      columns:
        - field: Value
          name: Comment
        - field: References
          name: Designator
        - Footprint
        - field: 'LCSC#'
          name: 'LCSC Part #'
      csv:
        hide_pcb_info: true
        hide_stats_info: true
        quote_all: true

  - name: 'interactive_bom (default)'
    comment: "Interactive Bill of Materials (HTML)"
    type: ibom
    options:
      blacklist: 'DNF*'
      dnf_filter:
        - 'exclude_gps_power_enable'
        
      name_format: '%f_iBoM'
        
  - name: 'schematic (full)'
    comment: "Print schematic (PDF)"
    type: pdf_sch_print
    dir: .
    options:
      output: Schematic.pdf

  - name: 'svg pcb (full)'
    comment: "Print schematic (PDF)"
    type: pcbdraw
    dir: .
    options:
      output: PCB.svg
      format: svg
      style:

        clad: "#242424"
        copper: "#242424"
        board: "#242424"
        silk: "#242424"
        pads: "#CCCCCC"
        outline: "#000000"
        highlight-on-top: false
        highlight-style: stroke:none;fill:#ff0000;opacity:0.5;
        highlight-padding: 1.5
        highlight-offset: 0
                # Meshtastic green #67EA94
