name: Build JLCPCB Gerber

on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v1
      with:
        config: jlcpcb.gerber.config.kibot.yaml
      # optional - prefix to output defined in config
        dir: Gerber
        schema: '*.sch'
        board: '*.kicad_pcb'
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Gerber
        path: Gerber
