name: Build and Release Artifacts

on:
  push:
    paths:
    - '*.properties'
#     - '*.yaml'
#     - '*.yml'
  workflow_dispatch:
  
jobs:
          
  Build-Full:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v1
      with:
        config: jlcpcb.full.config.kibot.yaml
        dir: Full
        schema: 'meshtastic-diy.sch'
        board: 'meshtastic-diy.kicad_pcb'
    - name: Show artifacts # For diagnostics
      run: ls -lR 
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Full.zip
        path: Full
  
  # Build-PSRAM:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: INTI-CMNB/KiBot@v1
  #     with:
  #       config: jlcpcb.psram.config.kibot.yaml
  #       dir: PSRAM
  #       schema: 'meshtastic-diy.sch'
  #       board: 'meshtastic-diy.kicad_pcb'
  #   - name: Show artifacts # For diagnostics
  #     run: ls -lR 
  #   - name: Upload artifacts
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: PSRAM.zip
  #       path: PSRAM

  # Build-AutoProg:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: INTI-CMNB/KiBot@v1
  #     with:
  #       config: jlcpcb.psram.config.kibot.yaml
  #       dir: AutoProg
  #       schema: 'meshtastic-diy.sch'
  #       board: 'meshtastic-diy.kicad_pcb'
  #   - name: Show artifacts # For diagnostics
  #     run: ls -lR 
  #   - name: Upload artifacts
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: AutoProg.zip
  #       path: AutoProg

  Build-Core:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v1
      with:
        config: jlcpcb.core.config.kibot.yaml
        dir: Core
        schema: 'meshtastic-diy.sch'
        board: 'meshtastic-diy.kicad_pcb'
    - name: Show artifacts # For diagnostics
      run: ls -lR 
    - name: Zip variant artifacts
      run: zip NoPSRAM+NoAuto-Prog.zip ./Core/* -r
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: NoPSRAM+NoAuto-Prog.zip
        path: ./
    
  Release-Artifacts:
    name: Release Artifacts
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      # NO_PSRAM_VARIANT: 'autoprog'
      # NO_PSRAM_FILE_LABEL: '(No PSRAM)'
      # NO_AUTO_PROG_VARIANT: 'psram'
      # NO_AUTO_PROG_FILE_LABEL: '(No Auto-prog)'
      # NO_PSRAM_NO_AUTO_PROG_VARIANT: 'core'
      # NO_PSRAM_NO_AUTO_PROG_FILE_LABEL: '(No PSRAM No Auto-prog)'

    needs: [Build-Full, Build-Core] #Build-PSRAM, Build-AutoProg]
    steps:
      - uses: actions/checkout@v1
      - name: Set Major Version
        id: major_version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './version.properties'
          property: 'MAJOR'
          
      - name: Set Minor Version
        id: minor_version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './version.properties'
          property: 'MINOR'
          
      - name: Set Release Version
        id: set_release_version
        run: echo ::set-env name=RELEASE_VERSION::${{ steps.major_version.outputs.value }}.${{ steps.minor_version.outputs.value }}
         
      - name: Download core
        id: download_core
        uses: actions/download-artifact@master
        with:
          name: NoPSRAM+NoAuto-Prog.zip
          path: ./
      
      - name: Download full
        id: download_full
        uses: actions/download-artifact@master
        with:
          name: Full.zip
          path: ./

      - name: Show artifacts # For diagnostics
        run: ls -lR 
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: v${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: true

      - name: Upload Release BoM
        id: upload-release-bom 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./meshtastic-diy_bom_jlc.csv
          asset_name: BoM-JLCPCB.${{ env.RELEASE_VERSION }}.csv
          asset_content_type: text/csv

      - name: Upload Release CPL
        id: upload-release-cpl 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./meshtastic-diy_cpl_jlc.csv
          asset_name: CPL-JLCPCB.${{ env.RELEASE_VERSION }}.csv
          asset_content_type: text/csv

      - name: Upload Release iBoM
        id: upload-release-ibom 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./meshtastic-diy-ibom.html
          asset_name: Interactive-BoM.${{ env.RELEASE_VERSION }}.html
          asset_content_type: text/html

      - name: Upload Release Gerber
        id: upload-release-gerber 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./JLCPCB/meshtastic-diy-JLCPCB.zip
          asset_name: Gerber-JLCPCB.${{ env.RELEASE_VERSION }}.zip
          asset_content_type: application/zip
          
      # SCHEMATIC 

      - name: Upload Release Schematic
        id: upload-release-schematic
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Schematic.pdf
          asset_name: Schematic.${{ env.RELEASE_VERSION }}.pdf
          asset_content_type: application/pdf
      
      # RENDERS
        
      - name: Upload Release STP
        id: upload-release-stp 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./PCB-Model.stp
          asset_name: PCB-Model.${{ env.RELEASE_VERSION }}.stp
          asset_content_type: application/octet-stream
          
      - name: Upload Release Board Render Top
        id: upload-release-render-top 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./PCB-Top.jpg
          asset_name: PCB-Top.${{ env.RELEASE_VERSION }}.jpg
          asset_content_type: image/jpeg
          
      - name: Upload Release Board Render Bottom
        id: upload-release-render-bottom 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./PCB-Bottom.jpg
          asset_name: PCB-Bottom.${{ env.RELEASE_VERSION }}.jpg
          asset_content_type: image/jpeg

      - name: Upload Core
        id: upload-release-core 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./NoPSRAM+NoAuto-Prog.zip
          asset_name: NoPSRAM+NoAuto-Prog.${{ env.RELEASE_VERSION }}.zip
          asset_content_type: application/zip