name: Build and Release Artifacts

on:
  push:
    paths:
    - '*.properties'
#     - '*.yaml'
#     - '*.yml'
  workflow_dispatch:
  
jobs:
          
  Build-Gerber:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v1
      with:
        config: jlcpcb.gerber.config.kibot.yaml
        dir: Gerber
        schema: 'meshtastic-diy.sch'
        board: 'meshtastic-diy.kicad_pcb'
    - name: Show artifacts # For diagnostics
      run: ls -lR 
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Gerber.zip
        path: Gerber

  Build-BOM:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v1
      with:
        config: jlcpcb.bom.config.kibot.yaml
        dir: BOM
        schema: 'meshtastic-diy.sch'
        board: 'meshtastic-diy.kicad_pcb'
    - name: Show artifacts # For diagnostics
      run: ls -lR
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: BOM.zip
        path: BOM
        
  Build-Renders:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v1
      with:
        config: jlcpcb.render.config.kibot.yaml
        dir: Render
        schema: 'meshtastic-diy.sch'
        board: 'meshtastic-diy.kicad_pcb'
    - name: Show artifacts # For diagnostics
      run: ls -lR 
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Render.zip
        path: Render       


  Release-Artifacts:
    name: Release Artifacts
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      NO_PSRAM_VARIANT: 'autoprog'
      NO_PSRAM_FILE_LABEL: '(No PSRAM)'
      NO_AUTO_PROG_VARIANT: 'psram'
      NO_AUTO_PROG_FILE: '(No Auto-prog)'
      NO_PSRAM_NO_AUTO_PROG_VARIANT: 'core'
      NO_PSRAM_NO_AUTO_PROG_FILE: '(No PSRAM No Auto-prog)'

    needs: [Build-Gerber, Build-BOM, Build-Renders]
    steps:
      - uses: actions/checkout@v1
      - name: Set Major Version
        id: major_version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './version.properties'
          property: 'MAJOR'
          
      - name: Set Minor Version
        id: minor_version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './version.properties'
          property: 'MINOR'
          
      - name: Set Release Version
        id: set_release_version
        run: echo ::set-env name=RELEASE_VERSION::${{ steps.major_version.outputs.value }}.${{ steps.minor_version.outputs.value }}
         
      - name: Download Gerber
        id: download_gerber
        uses: actions/download-artifact@master
        with:
          name: Gerber.zip
          path: ./
          
      - name: Download BOM
        id: download_bom
        uses: actions/download-artifact@master
        with:
          name: BOM.zip
          path: ./
               
      - name: Download Render
        id: download_render
        uses: actions/download-artifact@master
        with:
          name: Render.zip
          path: ./
          
      - name: Show artifacts # For diagnostics
        run: ls -lR 
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: v${{ env.RELEASE_VERSION }} Full
          draft: false
          prerelease: true

      - name: Upload Release BoM
        id: upload-release-bom 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./meshtastic-diy_bom_jlc.csv
          asset_name: BoM-JLCPCB.${{ env.RELEASE_VERSION }}.csv
          asset_content_type: text/csv
          
      - name: Upload Release CPL
        id: upload-release-cpl 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./meshtastic-diy_cpl_jlc.csv
          asset_name: CPL-JLCPCB.${{ env.RELEASE_VERSION }}.csv
          asset_content_type: text/csv

      - name: Upload Release CPL (No Auto prog)
        id: upload-release-cpl-auto-prog
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./meshtastic-diy_cpl_jlc_${{ env.NO_AUTO_PROG_VARIANT }}.csv
          asset_name: ${{ env.NO_AUTO_PROG_FILE }}CPL-JLCPCB.${{ env.RELEASE_VERSION }}.csv
          asset_content_type: text/csv

      - name: Upload Release CPL (No PSRAM)
        id: upload-release-cpl-psram
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./meshtastic-diy_cpl_jlc_${{ env.NO_PSRAM_VARIANT }}.csv
          asset_name: ${{ env.NO_PSRAM_FILE }}CPL-JLCPCB.${{ env.RELEASE_VERSION }}.csv
          asset_content_type: text/csv

      - name: Upload Release CPL (No Auto-prog / PSRAM )
        id: upload-release-cpl-core-parts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./meshtastic-diy_cpl_jlc_${{ env.NO_PSRAM_NO_AUTO_PROG_VARIANT }}.csv
          asset_name: ${{ env.NO_PSRAM_NO_AUTO_PROG_FILE }}CPL-JLCPCB.${{ env.RELEASE_VERSION }}.csv
          asset_content_type: text/csv
    
      - name: Upload Release iBoM
        id: upload-release-ibom 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./BoM/meshtastic-diy-ibom.html
          asset_name: Interactive-BoM.${{ env.RELEASE_VERSION }}.html
          asset_content_type: text/html
          
      - name: Upload Release Gerber
        id: upload-release-gerber 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./JLCPCB/meshtastic-diy-JLCPCB.zip
          asset_name: Gerber-JLCPCB.${{ env.RELEASE_VERSION }}.zip
          asset_content_type: application/zip
          
      - name: Upload Release Schematic
        id: upload-release-schematic 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Schematic.pdf
          asset_name: Schematic.${{ env.RELEASE_VERSION }}.pdf
          asset_content_type: application/pdf

      # RENDERS
        
      - name: Upload Release STP
        id: upload-release-stp 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./PCB-Model.stp
          asset_name: PCB-Model.${{ env.RELEASE_VERSION }}.stp
          asset_content_type: application/octet-stream
          
      - name: Upload Release Board Render Top
        id: upload-release-render-top 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./PCB-Top.jpg
          asset_name: PCB-Top.${{ env.RELEASE_VERSION }}.jpg
          asset_content_type: image/jpeg
          
      - name: Upload Release Board Render Bottom
        id: upload-release-render-bottom 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./PCB-Bottom.jpg
          asset_name: PCB-Bottom.${{ env.RELEASE_VERSION }}.jpg
          asset_content_type: image/jpeg
